import ReplayKit
import VideoToolbox
import CryptoKit
import CoreMedia
import AVFoundation
import Security

/**
 The extension implementation managing backpressure (atomic frame drops), GPU conversions, and autoreleasepool memory cleanup to respect the 50MB runtime boundary.
 */
/**
 SampleHandler.swift : Custom serial queue managing backpressure via an active frame-dropping flag (isProcessingFrame), automatic release of raw CVPixelBuffer resources through autoreleasepool, and AES-GCM encryption with keys retrieved from the Shared Keychain.
 */
public class SampleHandler: RPBroadcastSampleHandler {
    
    // Low-overhead serial queue to prevent thread explosion
    private let videoProcessingQueue = DispatchQueue(
        label: "com.example.app.video-processing",
        qos: .userInteractive
    )
    
    // Atomic-like access flag to prevent queue backpressure buildup
    private var isProcessingFrame = false
    private let isProcessingFrameQueue = DispatchQueue(label: "com.example.app.isProcessingFrameSync")
    
    private var symmetricKey: SymmetricKey?
    private let ciContext = CIContext(options: [.useSoftwareRenderer: false])
    
    // Video writing variables
    private var assetWriter: AVAssetWriter?
    private var assetWriterInput: AVAssetWriterInput?
    private var pixelBufferAdaptor: AVAssetWriterInputPixelBufferAdaptor?
    private let writerQueue = DispatchQueue(label: "com.apkia.replaykitapp.broadcast-writer-queue")
    private var hasStartedSession = false
    private var videoSampleCount = 0
    private var receivedSampleCount = 0
    private var videoBufferCount = 0
    private var videoFormatDescription = ""
    
    // Ledger tracking
    private var frameCounter = 0
    private var sessionStartDate = Date()
    private var lastChainHash = "0000000000000000000000000000000000000000000000000000000000000000"
    private let groupID = "group.com.apkia.replaykitapp.shared"
    private var broadcastSessionID = ""
    private let outputDirectoryName = "BroadcastOutput"
    
    public override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
        print("🟣 [SampleHandler] broadcastStarted called — OUR CODE IS RUNNING; setupInfo=\(String(describing: setupInfo))")
        broadcastSessionID = UUID().uuidString

        // Load the shared symmetric key generated by the host app via Shared Keychain
        let keyTag = "com.apkia.replaykitapp.session-key"
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrAccount as String: keyTag,
            kSecAttrAccessGroup as String: groupID,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne
        ]
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        if status == errSecSuccess, let data = item as? Data {
            self.symmetricKey = SymmetricKey(data: data)
            print("🟣 [SampleHandler] Symmetric key loaded from keychain successfully")
        } else {
            print("🟣 [SampleHandler] Notice: Symmetric key lookup status: \(status)")
        }
        
        // Reset ledger state
        frameCounter = 0
        sessionStartDate = Date()
        lastChainHash = "0000000000000000000000000000000000000000000000000000000000000000"
        assetWriter = nil
        assetWriterInput = nil
        pixelBufferAdaptor = nil
        hasStartedSession = false
        videoSampleCount = 0
        receivedSampleCount = 0
        videoBufferCount = 0
        videoFormatDescription = ""
        
        // Clear any prior frame metadata from App Group
        if let defaults = UserDefaults(suiteName: groupID) {
            defaults.removeObject(forKey: "frameMetadata")
            defaults.set(false, forKey: "broadcastFinished")
            defaults.set(true, forKey: "broadcastActive")
            defaults.set(broadcastSessionID, forKey: "broadcastSessionID")
            defaults.set(0, forKey: "broadcastVideoSampleCount")
            defaults.set(0, forKey: "broadcastReceivedSampleCount")
            defaults.set(0, forKey: "broadcastVideoBufferCount")
            defaults.removeObject(forKey: "broadcastVideoFormat")
            defaults.removeObject(forKey: "broadcastWriterStatus")
            defaults.removeObject(forKey: "broadcastWriterError")
            defaults.removeObject(forKey: "broadcastWriterErrorDomain")
            defaults.removeObject(forKey: "broadcastWriterErrorCode")
            defaults.synchronize()
            print("🟣 [SampleHandler] App Group UserDefaults reset OK")
        } else {
            print("🔴 [SampleHandler] ERROR: UserDefaults(suiteName:) returned nil — App Group NOT accessible!")
        }
        
        // Initialize AVAssetWriter in the shared App Group directory
        if let containerURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: groupID) {
            let outputDirectory = containerURL.appendingPathComponent(outputDirectoryName, isDirectory: true)
            do {
                try FileManager.default.createDirectory(at: outputDirectory, withIntermediateDirectories: true)
            } catch {
                print("🔴 [SampleHandler] Could not create output directory: \(error)")
            }
            let fileURL = outputDirectory.appendingPathComponent("broadcast.mp4")
            print("🟣 [SampleHandler] App Group container OK — fileURL: \(fileURL)")
            if FileManager.default.fileExists(atPath: fileURL.path) {
                try? FileManager.default.removeItem(at: fileURL)
                print("🟣 [SampleHandler] Removed previous broadcast.mp4")
            }
            do {
                assetWriter = try AVAssetWriter(url: fileURL, fileType: .mp4)
                print("🟣 [SampleHandler] AVAssetWriter created successfully")
            } catch {
                print("🔴 [SampleHandler] Failed to create AVAssetWriter: \(error)")
            }
        } else {
            print("🔴 [SampleHandler] ERROR: containerURL returned nil — App Group ID mismatch or entitlement issue!")
        }
    }
    
    public override func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        receivedSampleCount += 1
        switch sampleBufferType {
        case .video:
            videoBufferCount += 1
            if videoFormatDescription.isEmpty,
               let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) {
                videoFormatDescription = "\(CVPixelBufferGetWidth(imageBuffer))x\(CVPixelBufferGetHeight(imageBuffer)), pixelFormat=\(CVPixelBufferGetPixelFormatType(imageBuffer))"
            }
            // 1. ALWAYS send video frames to AVAssetWriter so the recording file receives full 60 FPS screen frames
            self.appendFrameToAssetWriter(sampleBuffer)
            
            // 2. Query current processing status for encryption/ledger processing
            var processing = false
            isProcessingFrameQueue.sync {
                processing = self.isProcessingFrame
            }
            
            // Backpressure Handling: If encryption/ledger pipeline is busy, drop encryption frame
            guard !processing else { return }
            
            isProcessingFrameQueue.sync {
                self.isProcessingFrame = true
            }
            
            videoProcessingQueue.async { [weak self] in
                guard let self = self else { return }
                
                // Memory Isolation: Force immediate release of high-memory video/graphics structures
                autoreleasepool {
                    self.encryptAndStreamFrame(sampleBuffer)
                }
                
                self.isProcessingFrameQueue.sync {
                    self.isProcessingFrame = false
                }
            }
            
        case .audioApp, .audioMic:
            // Handle audio frames if required
            break
            
        @unknown default:
            break
        }
    }
    
    public override func broadcastFinished() {
        let semaphore = DispatchSemaphore(value: 0)
        writerQueue.async { [weak self] in
            guard let self = self else {
                semaphore.signal()
                return
            }
            self.assetWriterInput?.markAsFinished()
            if let writer = self.assetWriter, writer.status == .writing {
                writer.finishWriting {
                    self.publishWriterDiagnostics(writer)
                    semaphore.signal()
                }
            } else {
                if let writer = self.assetWriter {
                    self.publishWriterDiagnostics(writer)
                }
                semaphore.signal()
            }
        }
        _ = semaphore.wait(timeout: .now() + 5.0)
        
        // Signal host app that broadcast has finished
        if let defaults = UserDefaults(suiteName: groupID) {
            defaults.set(broadcastSessionID, forKey: "broadcastFinishedSessionID")
            defaults.set(videoSampleCount, forKey: "broadcastVideoSampleCount")
            defaults.set(videoBufferCount, forKey: "broadcastVideoBufferCount")
            defaults.set(videoFormatDescription, forKey: "broadcastVideoFormat")
            defaults.set(receivedSampleCount, forKey: "broadcastReceivedSampleCount")
            defaults.set(false, forKey: "broadcastActive")
            defaults.set(true, forKey: "broadcastFinished")
            defaults.synchronize()
        }
    }
    
    public override func broadcastPaused() {
        // User has requested to pause the broadcast. Samples will stop being delivered.
    }
    
    public override func broadcastResumed() {
        // User has requested to resume the broadcast. Samples delivery will resume.
    }
    
    private func appendFrameToAssetWriter(_ sampleBuffer: CMSampleBuffer) {
        guard CMSampleBufferGetImageBuffer(sampleBuffer) != nil,
              let writer = assetWriter else {
            return
        }
        
        let pts = CMSampleBufferGetPresentationTimeStamp(sampleBuffer)
        guard pts.isValid else { return }
        
        writerQueue.async { [weak self] in
            guard let self = self else { return }
            
            if self.assetWriterInput == nil {
                guard let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return }
                let rawWidth = CVPixelBufferGetWidth(imageBuffer)
                let rawHeight = CVPixelBufferGetHeight(imageBuffer)
                let width = (rawWidth / 2) * 2
                let height = (rawHeight / 2) * 2
                
                let outputSettings: [String: Any] = [
                    AVVideoCodecKey: AVVideoCodecType.h264,
                    AVVideoWidthKey: width,
                    AVVideoHeightKey: height
                ]
                
                let input = AVAssetWriterInput(mediaType: .video, outputSettings: outputSettings)
                input.expectsMediaDataInRealTime = true

                let sourcePixelBufferAttributes: [String: Any] = [
                    // ReplayKit commonly delivers 420f on physical devices.
                    // Feed the adaptor a predictable BGRA buffer instead of
                    // relying on the H.264 writer to accept that source format.
                    kCVPixelBufferPixelFormatTypeKey as String: Int(kCVPixelFormatType_32BGRA),
                    kCVPixelBufferWidthKey as String: width,
                    kCVPixelBufferHeightKey as String: height
                ]
                let adaptor = AVAssetWriterInputPixelBufferAdaptor(
                    assetWriterInput: input,
                    sourcePixelBufferAttributes: sourcePixelBufferAttributes
                )
                
                if writer.canAdd(input) {
                    writer.add(input)
                    self.assetWriterInput = input
                    self.pixelBufferAdaptor = adaptor
                } else {
                    print("SampleHandler: Cannot add video input to AVAssetWriter")
                    return
                }
            }
            
            guard let input = self.assetWriterInput,
                  let adaptor = self.pixelBufferAdaptor,
                  let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return }
            
            if writer.status == .unknown {
                guard writer.startWriting() else {
                    print("🔴 [SampleHandler] AVAssetWriter could not start: \(String(describing: writer.error))")
                    return
                }
                writer.startSession(atSourceTime: pts)
                self.hasStartedSession = true
            }
            
            if writer.status == .writing && input.isReadyForMoreMediaData && self.hasStartedSession {
                guard let bgraBuffer = self.makeBGRAOutputBuffer(from: imageBuffer) else {
                    print("🔴 [SampleHandler] Could not convert ReplayKit pixel buffer to BGRA")
                    return
                }
                if !adaptor.append(bgraBuffer, withPresentationTime: pts) {
                    self.printWriterError("append", writer)
                } else {
                    self.videoSampleCount += 1
                }
            } else if writer.status == .failed {
                self.printWriterError("status", writer)
            }
        }
    }

    private func publishWriterDiagnostics(_ writer: AVAssetWriter) {
        guard let defaults = UserDefaults(suiteName: groupID) else { return }
        defaults.set(videoSampleCount, forKey: "broadcastVideoSampleCount")
        defaults.set(videoBufferCount, forKey: "broadcastVideoBufferCount")
        defaults.set(videoFormatDescription, forKey: "broadcastVideoFormat")
        defaults.set(writer.status.rawValue, forKey: "broadcastWriterStatus")
        if writer.status == .failed, let error = writer.error {
            let nsError = error as NSError
            defaults.set(error.localizedDescription, forKey: "broadcastWriterError")
            defaults.set(nsError.domain, forKey: "broadcastWriterErrorDomain")
            defaults.set(nsError.code, forKey: "broadcastWriterErrorCode")
        }
        defaults.synchronize()
        print("🟣 [SampleHandler] writer finished: status=\(writer.status.rawValue), videoBuffers=\(videoBufferCount), samples=\(videoSampleCount), format=\(videoFormatDescription), error=\(String(describing: writer.error))")
    }

    private func printWriterError(_ operation: String, _ writer: AVAssetWriter) {
        guard let error = writer.error else {
            print("🔴 [SampleHandler] AVAssetWriter \(operation) failed without an NSError")
            return
        }
        let nsError = error as NSError
        print("🔴 [SampleHandler] AVAssetWriter \(operation) failed: domain=\(nsError.domain) code=\(nsError.code) description=\(nsError.localizedDescription) userInfo=\(nsError.userInfo)")
    }

    private func makeBGRAOutputBuffer(from sourceBuffer: CVPixelBuffer) -> CVPixelBuffer? {
        let width = CVPixelBufferGetWidth(sourceBuffer)
        let height = CVPixelBufferGetHeight(sourceBuffer)
        var outputBuffer: CVPixelBuffer?
        let status = CVPixelBufferCreate(
            kCFAllocatorDefault,
            width,
            height,
            kCVPixelFormatType_32BGRA,
            [
                kCVPixelBufferCGImageCompatibilityKey: true,
                kCVPixelBufferCGBitmapContextCompatibilityKey: true,
                kCVPixelBufferMetalCompatibilityKey: true
            ] as CFDictionary,
            &outputBuffer
        )
        guard status == kCVReturnSuccess, let outputBuffer else { return nil }

        let image = CIImage(cvPixelBuffer: sourceBuffer)
        ciContext.render(
            image,
            to: outputBuffer,
            bounds: CGRect(x: 0, y: 0, width: width, height: height),
            colorSpace: CGColorSpaceCreateDeviceRGB()
        )
        return outputBuffer
    }
    
    private func encryptAndStreamFrame(_ sampleBuffer: CMSampleBuffer) {
        // 1. Extract raw image buffer
        guard let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return }
        
        frameCounter += 1
        
        // 2. Convert to JPEG for encryption payload using shared ciContext
        let ciImage = CIImage(cvImageBuffer: imageBuffer)
        let colorSpace = ciImage.colorSpace ?? CGColorSpaceCreateDeviceRGB()
        
        guard let jpegData = self.ciContext.jpegRepresentation(
            of: ciImage,
            colorSpace: colorSpace,
            options: [:]
        ) else { return }
        
        // 3. Compute SHA-256 — respect active pipeline stored in shared UserDefaults
        let pipelineRaw = UserDefaults(suiteName: groupID)?.string(forKey: "captureSettings.hashingPipeline") ?? "pixelBuffer"
        let frameHash: String
        if pipelineRaw == "jpegFirst" {
            // Pipeline 2: hash the JPEG bytes
            let digest = SHA256.hash(data: jpegData)
            frameHash = digest.compactMap { String(format: "%02x", $0) }.joined()
        } else {
            // Pipeline 1 (default): hash raw pixel buffer bytes
            CVPixelBufferLockBaseAddress(imageBuffer, .readOnly)
            defer { CVPixelBufferUnlockBaseAddress(imageBuffer, .readOnly) }
            if let base = CVPixelBufferGetBaseAddress(imageBuffer) {
                let bytes = CVPixelBufferGetBytesPerRow(imageBuffer) * CVPixelBufferGetHeight(imageBuffer)
                let ptr = UnsafeRawBufferPointer(start: base, count: bytes)
                let digest = SHA256.hash(data: ptr)
                frameHash = digest.compactMap { String(format: "%02x", $0) }.joined()
            } else {
                frameHash = ""
            }
        }
        
        // 4. Hash chain
        let prevHash = lastChainHash
        let chainInput = frameHash + prevHash
        let chainHash = SHA256.hash(data: Data(chainInput.utf8)).compactMap { String(format: "%02x", $0) }.joined()
        lastChainHash = chainHash

        let elapsed = Date().timeIntervalSince(sessionStartDate)
        let minutes = Int(elapsed) / 60
        let seconds = Int(elapsed) % 60
        let ms = Int((elapsed.truncatingRemainder(dividingBy: 1.0)) * 1000)
        let timestamp = String(format: "%02d:%02d.%03d", minutes, seconds, ms)

        // Persist the authenticated frame payload and thumbnail for the
        // post-session encrypted gallery. The UI ledger remains lightweight.
        if let key = symmetricKey {
            let width = CVPixelBufferGetWidth(imageBuffer)
            let height = CVPixelBufferGetHeight(imageBuffer)
            let scale: CGFloat = 360.0 / CGFloat(width)
            let scaledImage = ciImage.transformed(by: CGAffineTransform(scaleX: scale, y: scale))
            var thumbnailData: Data?
            if let cgImg = self.ciContext.createCGImage(scaledImage, from: scaledImage.extent) {
                thumbnailData = UIImage(cgImage: cgImg).jpegData(compressionQuality: 0.5)
            }
            let metadata = StoredFrameMetadata(
                index: frameCounter,
                timestamp: timestamp,
                sizeKB: String(format: "%.1f KB", Double(jpegData.count) / 1024.0),
                rawSize: jpegData.count,
                sha256: frameHash,
                previousHash: prevHash,
                chainHash: chainHash,
                sessionID: broadcastSessionID,
                resolution: "\(width) × \(height)"
            )
            do {
                try EncryptedFrameStore.shared.persist(
                    payload: jpegData,
                    thumbnail: thumbnailData,
                    metadata: metadata,
                    using: key
                )
            } catch {
                print("Encrypted frame-store write failed: \(error)")
            }
        }

        // 5. Every 10th frame: write ledger record to shared App Group UserDefaults
        if frameCounter % 10 == 0 {
            let width = CVPixelBufferGetWidth(imageBuffer)
            let height = CVPixelBufferGetHeight(imageBuffer)
            
            let entry: [String: Any] = [
                "index": frameCounter,
                "timestamp": timestamp,
                "sizeKB": String(format: "%.1f KB", Double(jpegData.count) / 1024.0),
                "rawSize": jpegData.count,
                "sha256": frameHash,
                "previousHash": prevHash,
                "chainHash": chainHash,
                "sessionID": broadcastSessionID,
                "resolution": "\(width) × \(height)"
            ]
            
            if let defaults = UserDefaults(suiteName: groupID) {
                var existing = defaults.array(forKey: "frameMetadata") as? [[String: Any]] ?? []
                existing.append(entry)
                // Keep only last 20
                if existing.count > 20 { existing.removeFirst(existing.count - 20) }
                defaults.set(existing, forKey: "frameMetadata")
                defaults.synchronize()
            }
        }
        
        // 6. AES-GCM Encrypt the JPEG payload
        guard let key = self.symmetricKey else {
            self.sendToNetwork(jpegData)
            return
        }
        
        do {
            let sealedBox = try AES.GCM.seal(jpegData, using: key)
            self.sendToNetwork(sealedBox.combined)
        } catch {
            print("Encryption failed in SampleHandler: \(error)")
        }
    }
    
    private func sendToNetwork(_ data: Data?) {
        // Placeholder for WebRTC client pipeline or gRPC streaming connection.
        // In production, frame data is written to a Unix Domain Socket or passed to WebRTC data channel.
    }
}
