import ReplayKit
import VideoToolbox
import CryptoKit
import CoreMedia
import AVFoundation

/**
 The extension implementation managing backpressure (atomic frame drops), GPU conversions, and autoreleasepool memory cleanup to respect the 50MB runtime boundary.
 */
/**
 SampleHandler.swift : Custom serial queue managing backpressure via an active frame-dropping flag (isProcessingFrame), automatic release of raw CVPixelBuffer resources through autoreleasepool, and AES-GCM encryption with keys retrieved from the Shared Keychain.
 */
public class SampleHandler: RPBroadcastSampleHandler {
    
    // Low-overhead serial queue to prevent thread explosion (GCD queue limits scheduler overhead)
    private let videoProcessingQueue = DispatchQueue(
        label: "com.example.app.video-processing",
        qos: .userInteractive
    )
    
    // Atomic-like access flag to prevent queue backpressure buildup
    private var isProcessingFrame = false
    private let isProcessingFrameQueue = DispatchQueue(label: "com.example.app.isProcessingFrameSync")
    
    private var symmetricKey: SymmetricKey?
    
    // Video writing variables
    private var assetWriter: AVAssetWriter?
    private var assetWriterInput: AVAssetWriterInput?
    private let writerQueue = DispatchQueue(label: "com.apkia.replaykitapp.broadcast-writer-queue")
    private var hasStartedSession = false
    
    public override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
        // Load the shared symmetric key generated by the host app via Shared Keychain
        do {
            if let key = try SharedKeychainManager.shared.getSymmetricKey() {
                self.symmetricKey = key
            } else {
                print("Warning: Symmetric key not found in shared keychain. Broadcasting in unencrypted mode or waiting for key.")
            }
        } catch {
            print("Failed to retrieve symmetric key from Shared Keychain: \(error)")
        }
        
        // Initialize AVAssetWriter in the shared App Group directory
        let groupID = "group.com.apkia.replaykitapp.shared-group"
        if let containerURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: groupID) {
            let fileURL = containerURL.appendingPathComponent("broadcast.mp4")
            if FileManager.default.fileExists(atPath: fileURL.path) {
                try? FileManager.default.removeItem(at: fileURL)
            }
            do {
                assetWriter = try AVAssetWriter(url: fileURL, fileType: .mp4)
            } catch {
                print("Failed to create AVAssetWriter in Broadcast Extension: \(error)")
            }
        }
    }
    
    public override func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        switch sampleBufferType {
        case .video:
            // Query current processing status in a thread-safe manner
            var processing = false
            isProcessingFrameQueue.sync {
                processing = self.isProcessingFrame
            }
            
            // Backpressure Handling: If the encryption pipeline is busy, drop this frame immediately.
            // Under 50MB extension constraint, queued frames are the leading cause of memory growth.
            guard !processing else { return }
            
            isProcessingFrameQueue.sync {
                self.isProcessingFrame = true
            }
            
            videoProcessingQueue.async { [weak self] in
                guard let self = self else { return }
                
                // Memory Isolation: Force immediate release of high-memory video/graphics structures
                autoreleasepool {
                    self.encryptAndStreamFrame(sampleBuffer)
                    self.appendFrameToAssetWriter(sampleBuffer)
                }
                
                self.isProcessingFrameQueue.sync {
                    self.isProcessingFrame = false
                }
            }
            
        case .audioApp, .audioMic:
            // Handle audio frames if required
            break
            
        @unknown default:
            break
        }
    }
    
    public override func broadcastFinished() {
        let semaphore = DispatchSemaphore(value: 0)
        writerQueue.async { [weak self] in
            guard let self = self else {
                semaphore.signal()
                return
            }
            self.assetWriterInput?.markAsFinished()
            if let writer = self.assetWriter, writer.status == .writing {
                writer.finishWriting {
                    semaphore.signal()
                }
            } else {
                semaphore.signal()
            }
        }
        _ = semaphore.wait(timeout: .now() + 5.0)
    }
    
    private func appendFrameToAssetWriter(_ sampleBuffer: CMSampleBuffer) {
        guard let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer),
              let writer = assetWriter else { return }
        
        writerQueue.async { [weak self] in
            guard let self = self else { return }
            
            if self.assetWriterInput == nil {
                let width = CVPixelBufferGetWidth(imageBuffer)
                let height = CVPixelBufferGetHeight(imageBuffer)
                
                let outputSettings: [String: Any] = [
                    AVVideoCodecKey: AVVideoCodecType.h264,
                    AVVideoWidthKey: width,
                    AVVideoHeightKey: height
                ]
                
                let input = AVAssetWriterInput(mediaType: .video, outputSettings: outputSettings)
                input.expectsMediaDataInRealTime = true
                
                if writer.canAdd(input) {
                    writer.add(input)
                    self.assetWriterInput = input
                } else {
                    return
                }
            }
            
            guard let input = self.assetWriterInput else { return }
            
            if writer.status == .unknown {
                writer.startWriting()
                writer.startSession(atSourceTime: CMSampleBufferGetPresentationTimeStamp(sampleBuffer))
                self.hasStartedSession = true
            }
            
            if writer.status == .writing && input.isReadyForMoreMediaData && self.hasStartedSession {
                input.append(sampleBuffer)
            }
        }
    }
    
    private func encryptAndStreamFrame(_ sampleBuffer: CMSampleBuffer) {
        // 1. Extract raw image buffer
        guard let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return }
        
        // 2. Convert to JPEG/Data using GPU acceleration where possible to reduce CPU memory spikes
        let ciImage = CIImage(cvImageBuffer: imageBuffer)
        let context = CIContext(options: [.useSoftwareRenderer: false])
        
        // JPEG rendering with device color space
        guard let jpegData = context.jpegRepresentation(
            of: ciImage,
            colorSpace: CGColorSpaceCreateDeviceRGB(),
            options: [:]
        ) else { return }
        
        // 3. Ultra-fast AES-GCM Symmetric Encryption
        guard let key = self.symmetricKey else {
            // No key yet, fallback to local network stream or skip
            self.sendToNetwork(jpegData)
            return
        }
        
        do {
            let sealedBox = try AES.GCM.seal(jpegData, using: key)
            let encryptedPayload = sealedBox.combined // Safe payload to send over network
            
            // 4. Stream to WebRTC / Socket
            self.sendToNetwork(encryptedPayload)
        } catch {
            print("Encryption failed in SampleHandler: \(error)")
        }
    }
    
    private func sendToNetwork(_ data: Data?) {
        // Placeholder for WebRTC client pipeline or gRPC streaming connection.
        // In production, frame data is written to a Unix Domain Socket or passed to WebRTC data channel.
    }
}
