import ReplayKit
import VideoToolbox
import CryptoKit
import CoreMedia
import AVFoundation

/**
 The extension implementation managing backpressure (atomic frame drops), GPU conversions, and autoreleasepool memory cleanup to respect the 50MB runtime boundary.
 */
/**
 SampleHandler.swift : Custom serial queue managing backpressure via an active frame-dropping flag (isProcessingFrame), automatic release of raw CVPixelBuffer resources through autoreleasepool, and AES-GCM encryption with keys retrieved from the Shared Keychain.
 */
public class SampleHandler: RPBroadcastSampleHandler {
    
    // Low-overhead serial queue to prevent thread explosion
    private let videoProcessingQueue = DispatchQueue(
        label: "com.example.app.video-processing",
        qos: .userInteractive
    )
    
    // Atomic-like access flag to prevent queue backpressure buildup
    private var isProcessingFrame = false
    private let isProcessingFrameQueue = DispatchQueue(label: "com.example.app.isProcessingFrameSync")
    
    private var symmetricKey: SymmetricKey?
    
    // Video writing variables
    private var assetWriter: AVAssetWriter?
    private var assetWriterInput: AVAssetWriterInput?
    private let writerQueue = DispatchQueue(label: "com.apkia.replaykitapp.broadcast-writer-queue")
    private var hasStartedSession = false
    
    // Ledger tracking
    private var frameCounter = 0
    private var sessionStartDate = Date()
    private var lastChainHash = "0000000000000000000000000000000000000000000000000000000000000000"
    private let groupID = "group.com.apkia.replaykitapp.shared-group"
    
    public override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
        // Load the shared symmetric key generated by the host app via Shared Keychain
        do {
            if let key = try SharedKeychainManager.shared.getSymmetricKey() {
                self.symmetricKey = key
            } else {
                print("Warning: Symmetric key not found in shared keychain.")
            }
        } catch {
            print("Failed to retrieve symmetric key: \(error)")
        }
        
        // Reset ledger state
        frameCounter = 0
        sessionStartDate = Date()
        lastChainHash = "0000000000000000000000000000000000000000000000000000000000000000"
        
        // Clear any prior frame metadata from App Group
        if let defaults = UserDefaults(suiteName: groupID) {
            defaults.removeObject(forKey: "frameMetadata")
            defaults.set(false, forKey: "broadcastFinished")
            defaults.set(true, forKey: "broadcastActive")
            defaults.synchronize()
        }
        
        // Initialize AVAssetWriter in the shared App Group directory
        if let containerURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: groupID) {
            let fileURL = containerURL.appendingPathComponent("broadcast.mp4")
            if FileManager.default.fileExists(atPath: fileURL.path) {
                try? FileManager.default.removeItem(at: fileURL)
            }
            do {
                assetWriter = try AVAssetWriter(url: fileURL, fileType: .mp4)
            } catch {
                print("Failed to create AVAssetWriter: \(error)")
            }
        }
    }
    
    public override func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        switch sampleBufferType {
        case .video:
            // Query current processing status in a thread-safe manner
            var processing = false
            isProcessingFrameQueue.sync {
                processing = self.isProcessingFrame
            }
            
            // Backpressure Handling: If the encryption pipeline is busy, drop this frame immediately.
            // Under 50MB extension constraint, queued frames are the leading cause of memory growth.
            guard !processing else { return }
            
            isProcessingFrameQueue.sync {
                self.isProcessingFrame = true
            }
            
            videoProcessingQueue.async { [weak self] in
                guard let self = self else { return }
                
                // Memory Isolation: Force immediate release of high-memory video/graphics structures
                autoreleasepool {
                    self.encryptAndStreamFrame(sampleBuffer)
                    self.appendFrameToAssetWriter(sampleBuffer)
                }
                
                self.isProcessingFrameQueue.sync {
                    self.isProcessingFrame = false
                }
            }
            
        case .audioApp, .audioMic:
            // Handle audio frames if required
            break
            
        @unknown default:
            break
        }
    }
    
    public override func broadcastFinished() {
        let semaphore = DispatchSemaphore(value: 0)
        writerQueue.async { [weak self] in
            guard let self = self else {
                semaphore.signal()
                return
            }
            self.assetWriterInput?.markAsFinished()
            if let writer = self.assetWriter, writer.status == .writing {
                writer.finishWriting {
                    semaphore.signal()
                }
            } else {
                semaphore.signal()
            }
        }
        _ = semaphore.wait(timeout: .now() + 5.0)
        
        // Signal host app that broadcast has finished
        if let defaults = UserDefaults(suiteName: groupID) {
            defaults.set(false, forKey: "broadcastActive")
            defaults.set(true, forKey: "broadcastFinished")
            defaults.synchronize()
        }
    }
    
    public override func broadcastPaused() {
        // User has requested to pause the broadcast. Samples will stop being delivered.
    }
    
    public override func broadcastResumed() {
        // User has requested to resume the broadcast. Samples delivery will resume.
    }
    
    private func appendFrameToAssetWriter(_ sampleBuffer: CMSampleBuffer) {
        guard let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer),
              let writer = assetWriter else { return }
        
        writerQueue.async { [weak self] in
            guard let self = self else { return }
            
            if self.assetWriterInput == nil {
                let width = CVPixelBufferGetWidth(imageBuffer)
                let height = CVPixelBufferGetHeight(imageBuffer)
                
                let outputSettings: [String: Any] = [
                    AVVideoCodecKey: AVVideoCodecType.h264,
                    AVVideoWidthKey: width,
                    AVVideoHeightKey: height
                ]
                
                let input = AVAssetWriterInput(mediaType: .video, outputSettings: outputSettings)
                input.expectsMediaDataInRealTime = true
                
                if writer.canAdd(input) {
                    writer.add(input)
                    self.assetWriterInput = input
                } else {
                    return
                }
            }
            
            guard let input = self.assetWriterInput else { return }
            
            if writer.status == .unknown {
                writer.startWriting()
                writer.startSession(atSourceTime: CMSampleBufferGetPresentationTimeStamp(sampleBuffer))
                self.hasStartedSession = true
            }
            
            if writer.status == .writing && input.isReadyForMoreMediaData && self.hasStartedSession {
                input.append(sampleBuffer)
            }
        }
    }
    
    private func encryptAndStreamFrame(_ sampleBuffer: CMSampleBuffer) {
        // 1. Extract raw image buffer
        guard let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return }
        
        frameCounter += 1
        
        // 2. Convert to JPEG for encryption payload
        let ciImage = CIImage(cvImageBuffer: imageBuffer)
        let context = CIContext(options: [.useSoftwareRenderer: false])
        
        guard let jpegData = context.jpegRepresentation(
            of: ciImage,
            colorSpace: CGColorSpaceCreateDeviceRGB(),
            options: [:]
        ) else { return }
        
        // 3. Compute SHA-256 — respect active pipeline stored in shared UserDefaults
        let pipelineRaw = UserDefaults(suiteName: groupID)?.string(forKey: "captureSettings.hashingPipeline") ?? "pixelBuffer"
        let frameHash: String
        if pipelineRaw == "jpegFirst" {
            // Pipeline 2: hash the JPEG bytes
            let digest = SHA256.hash(data: jpegData)
            frameHash = digest.compactMap { String(format: "%02x", $0) }.joined()
        } else {
            // Pipeline 1 (default): hash raw pixel buffer bytes
            CVPixelBufferLockBaseAddress(imageBuffer, .readOnly)
            defer { CVPixelBufferUnlockBaseAddress(imageBuffer, .readOnly) }
            if let base = CVPixelBufferGetBaseAddress(imageBuffer) {
                let bytes = CVPixelBufferGetBytesPerRow(imageBuffer) * CVPixelBufferGetHeight(imageBuffer)
                let ptr = UnsafeRawBufferPointer(start: base, count: bytes)
                let digest = SHA256.hash(data: ptr)
                frameHash = digest.compactMap { String(format: "%02x", $0) }.joined()
            } else {
                frameHash = ""
            }
        }
        
        // 4. Hash chain
        let prevHash = lastChainHash
        let chainInput = frameHash + prevHash
        let chainHash = SHA256.hash(data: Data(chainInput.utf8)).compactMap { String(format: "%02x", $0) }.joined()
        lastChainHash = chainHash
        
        // 5. Every 10th frame: write ledger record to shared App Group UserDefaults
        if frameCounter % 10 == 0 {
            let elapsed = Date().timeIntervalSince(sessionStartDate)
            let minutes = Int(elapsed) / 60
            let seconds = Int(elapsed) % 60
            let ms = Int((elapsed.truncatingRemainder(dividingBy: 1.0)) * 1000)
            let timestamp = String(format: "%02d:%02d.%03d", minutes, seconds, ms)
            
            let width = CVPixelBufferGetWidth(imageBuffer)
            let height = CVPixelBufferGetHeight(imageBuffer)
            
            // Scale thumbnail to 80px wide
            let scale: CGFloat = 80.0 / CGFloat(width)
            let scaledImage = ciImage.transformed(by: CGAffineTransform(scaleX: scale, y: scale))
            var thumbBase64: String = ""
            if let cgImg = context.createCGImage(scaledImage, from: scaledImage.extent),
               let thumbData = UIImage(cgImage: cgImg).jpegData(compressionQuality: 0.5) {
                thumbBase64 = thumbData.base64EncodedString()
            }
            
            let entry: [String: Any] = [
                "index": frameCounter,
                "timestamp": timestamp,
                "sizeKB": String(format: "%.1f KB", Double(jpegData.count) / 1024.0),
                "rawSize": jpegData.count,
                "sha256": frameHash,
                "previousHash": prevHash,
                "chainHash": chainHash,
                "thumbBase64": thumbBase64,
                "resolution": "\(width) × \(height)"
            ]
            
            if let defaults = UserDefaults(suiteName: groupID) {
                var existing = defaults.array(forKey: "frameMetadata") as? [[String: Any]] ?? []
                existing.append(entry)
                // Keep only last 20
                if existing.count > 20 { existing.removeFirst(existing.count - 20) }
                defaults.set(existing, forKey: "frameMetadata")
                defaults.synchronize()
            }
        }
        
        // 6. AES-GCM Encrypt the JPEG payload
        guard let key = self.symmetricKey else {
            self.sendToNetwork(jpegData)
            return
        }
        
        do {
            let sealedBox = try AES.GCM.seal(jpegData, using: key)
            self.sendToNetwork(sealedBox.combined)
        } catch {
            print("Encryption failed in SampleHandler: \(error)")
        }
    }
    
    private func sendToNetwork(_ data: Data?) {
        // Placeholder for WebRTC client pipeline or gRPC streaming connection.
        // In production, frame data is written to a Unix Domain Socket or passed to WebRTC data channel.
    }
}
